apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api-deployment
  labels:
    app: udagram-users-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-users-api
  template:
    metadata:
      labels:
        app: udagram-users-api
    spec:
      containers:
        - name: udagram-api-users
          image: mpmaia/udagram-api-users
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: udagram
                  key: postgres_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: udagram
                  key: postgres_password
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: udagram
                  key: postgres_host
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: udagram
                  key: postgres_db
            - name: AWS_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: udagram
                  key: aws_bucket
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: udagram
                  key: aws_region
            - name: AWS_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: udagram
                  key: aws_profile
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: udagram
                  key: jwt_secret
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: udagram
                  key: url
          volumeMounts:
            - name: aws-credentials
              mountPath: /root/.aws/
              readOnly: true
          resources:
            requests:
              cpu: "250m"
            limits:
              cpu: "500m"
      volumes:
        - name: aws-credentials
          hostPath:
            path: /etc/aws
            type: Directory

